name = "Riinas Improved Minecraft"
author = "Riina"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2963efa158cd70c7e3479bd23ca29b2e11586e16288ae8f82cc3587eb39f2a0b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.235"
unsup = "1.2.7"
