name = "Riinas Improved Minecraft"
author = "Riina"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0ccfa6b3ce99554c13333e186ba1c49d122df130ab91ec1ca073c1d6d0071087"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.235"
unsup = "1.2.7"
