name = "Riinas Improved Minecraft"
author = "Riina"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "061e3df0e511734627e2e106e31bb60fc84fa99c1783affbc8f3b7aa0e1040d3"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.235"
unsup = "1.2.7"
